# Generated by Django 2.2.1 on 2019-05-22 22:10

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('posts', '0006_post_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publication_date',
        ),
    ]
