# Generated by Django 2.2.1 on 2019-05-24 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('posts', '0007_remove_post_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
