# Generated by Django 2.2.1 on 2019-05-24 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
